/**
 * 🌍 Auto-Translation Utility with GPT-4
 * 
 * Traduce automáticamente todas las keys de i18n
 * desde Español (base) a Inglés y Portugués
 */

import esTranslations from '../i18n/locales/es';
import { projectId, publicAnonKey } from './supabase/info';

interface TranslationObject {
  [key: string]: string | TranslationObject;
}

/**
 * Traduce un objeto completo usando GPT-4 via el servidor
 */
export async function translateWithGPT4(
  sourceText: TranslationObject,
  targetLanguage: 'en' | 'pt'
): Promise<TranslationObject> {
  const languageNames = {
    en: 'English',
    pt: 'Portuguese (Brazilian)',
  };

  console.log(`📡 Traduciendo a ${languageNames[targetLanguage]} con GPT-4...`);

  // Call our server endpoint instead of OpenAI directly
  const serverUrl = `https://${projectId}.supabase.co/functions/v1/make-server-727b50c3/translate`;
  
  const response = await fetch(serverUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${publicAnonKey}`,
    },
    body: JSON.stringify({
      sourceText,
      targetLanguage,
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(`Server translation error: ${error.error || response.statusText}`);
  }

  const data = await response.json();
  
  if (!data.success || !data.translated) {
    throw new Error('Invalid response from translation server');
  }

  console.log('📥 Respuesta recibida del servidor');

  return data.translated;
}

/**
 * Convierte objeto a formato TypeScript
 */
export function objectToTypeScript(obj: TranslationObject, indent = 0): string {
  const spaces = '  '.repeat(indent);
  let result = '{\n';

  const entries = Object.entries(obj);
  entries.forEach(([key, value], index) => {
    const isLast = index === entries.length - 1;
    
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      result += `${spaces}  ${key}: ${objectToTypeScript(value, indent + 1)}${isLast ? '' : ','}\n`;
    } else if (typeof value === 'string') {
      // Escapar comillas y caracteres especiales
      const escapedValue = value
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(/\n/g, '\\n');
      result += `${spaces}  ${key}: "${escapedValue}"${isLast ? '' : ','}\n`;
    } else {
      result += `${spaces}  ${key}: ${JSON.stringify(value)}${isLast ? '' : ','}\n`;
    }
  });

  result += `${spaces}}`;
  return result;
}

/**
 * Ejecuta la traducción automática completa
 */
export async function runAutoTranslation() {
  console.log('🌍 Iniciando auto-traducción con GPT-4...\n');
  console.log('📖 Usando español como idioma base');
  console.log(`📊 Total de secciones: ${Object.keys(esTranslations).length}\n`);

  const results = {
    en: null as TranslationObject | null,
    pt: null as TranslationObject | null,
    errors: [] as string[],
  };

  // Traducir a Inglés
  try {
    console.log('🇬🇧 Traduciendo a INGLÉS...');
    results.en = await translateWithGPT4(esTranslations, 'en');
    console.log('✅ Traducción a inglés completada\n');
  } catch (e: any) {
    const error = `Error traduciendo a inglés: ${e.message}`;
    console.error('❌', error);
    results.errors.push(error);
  }

  // Traducir a Portugués
  try {
    console.log('🇧🇷 Traduciendo a PORTUGUÉS...');
    results.pt = await translateWithGPT4(esTranslations, 'pt');
    console.log('✅ Traducción a portugués completada\n');
  } catch (e: any) {
    const error = `Error traduciendo a portugués: ${e.message}`;
    console.error('❌', error);
    results.errors.push(error);
  }

  // Generar archivos
  console.log('📝 Generando código TypeScript...\n');

  const files = {
    en: results.en ? generateTSFile(results.en, 'en', 'English') : null,
    pt: results.pt ? generateTSFile(results.pt, 'pt', 'Portuguese (Brazilian)') : null,
  };

  // Mostrar resultados
  console.log('='.repeat(60));
  console.log('✨ AUTO-TRADUCCIÓN COMPLETADA ✨');
  console.log('='.repeat(60));
  console.log(`📊 Resultados:`);
  console.log(`   • Inglés: ${results.en ? '✅ Completado' : '❌ Error'}`);
  console.log(`   • Portugués: ${results.pt ? '✅ Completado' : '❌ Error'}`);
  
  if (results.errors.length > 0) {
    console.log(`\n⚠️  Errores encontrados:`);
    results.errors.forEach(err => console.log(`   - ${err}`));
  }

  console.log('\n💾 Para guardar los archivos traducidos:');
  console.log('   1. Copia el contenido que se muestra abajo');
  console.log('   2. Pégalo en /i18n/locales/en.ts y /i18n/locales/pt.ts');
  console.log('='.repeat(60) + '\n');

  return { results, files };
}

function generateTSFile(translations: TranslationObject, lang: string, langName: string): string {
  return `/**
 * ${getFlagEmoji(lang)} ${langName} Translations
 * Auto-generated by auto-translate.ts
 * Base: Spanish (es.ts)
 * Generated: ${new Date().toISOString()}
 */

export default ${objectToTypeScript(translations, 0)};
`;
}

function getFlagEmoji(lang: string): string {
  const flags: Record<string, string> = {
    en: '🇬🇧',
    pt: '🇧🇷',
    es: '🇪🇸',
  };
  return flags[lang] || '🌍';
}